project:
  type: website
  output-dir: docs

website:
  title: "Mission: Lifeline Datathon Preparation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: examples.qmd
        text: Examples
      - href: learning.qmd
        text: Learning


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

